# Generated by Django 4.2.27 on 2026-01-13 14:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('police', 'Police'), ('normal_user', 'Normal User'), ('private_vehicle_owner', 'Private Vehicle Owner'), ('government_vehicle_owner', 'Government Vehicle Owner')], db_index=True, default='normal_user', help_text='User role for access control', max_length=30)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='User biography or description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, help_text='Unique vehicle identifier (e.g., registration number)', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('government', 'Government')], db_index=True, help_text='Type of vehicle', max_length=20)),
                ('make', models.CharField(blank=True, help_text='Vehicle manufacturer', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Vehicle model', max_length=100)),
                ('year', models.IntegerField(blank=True, help_text='Manufacturing year', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether vehicle is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Vehicle owner (can be null for public vehicles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, help_text='Unique route identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable route name', max_length=200)),
                ('start_location', models.CharField(help_text='Starting point name', max_length=200)),
                ('end_location', models.CharField(help_text='Ending point name', max_length=200)),
                ('start_latitude', models.FloatField(help_text='Start location latitude')),
                ('start_longitude', models.FloatField(help_text='Start location longitude')),
                ('end_latitude', models.FloatField(help_text='End location latitude')),
                ('end_longitude', models.FloatField(help_text='End location longitude')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Whether this is a public route (detected from repeated trips)')),
                ('trip_count', models.IntegerField(default=0, help_text='Number of trips on this route')),
                ('average_speed', models.FloatField(blank=True, help_text='Average speed on this route (m/s)', null=True)),
                ('average_duration', models.IntegerField(blank=True, help_text='Average trip duration (seconds)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routes',
                'indexes': [models.Index(fields=['route_id'], name='routes_route_i_e5bbdc_idx'), models.Index(fields=['is_public'], name='routes_is_publ_46fc76_idx'), models.Index(fields=['start_latitude', 'start_longitude'], name='routes_start_l_10126e_idx'), models.Index(fields=['end_latitude', 'end_longitude'], name='routes_end_lat_9754d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Location name', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude coordinate')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude coordinate')),
                ('location_type', models.CharField(choices=[('bus_stop', 'Bus Stop'), ('metro_station', 'Metro Station'), ('landmark', 'Landmark'), ('hospital', 'Hospital'), ('school', 'School'), ('restaurant', 'Restaurant'), ('shopping', 'Shopping'), ('office', 'Office'), ('residential', 'Residential'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('osm_id', models.BigIntegerField(blank=True, help_text='OpenStreetMap ID', null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, help_text='OSM type: node, way, relation', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Accessible to public/normal users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_routes', models.ManyToManyField(blank=True, help_text='Routes passing through this location', related_name='locations', to='Devices.route')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier (MAC address, IMEI, etc.)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('faulty', 'Faulty')], db_index=True, default='active', help_text='Current device status', max_length=20)),
                ('firmware_version', models.CharField(blank=True, help_text='Device firmware version', max_length=50)),
                ('last_ping', models.DateTimeField(blank=True, db_index=True, help_text='Last time device sent data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='Vehicle this device is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Devices.vehicle')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type', 'is_active'], name='vehicles_vehicle_ce02a9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', 'vehicle_type'], name='vehicles_owner_i_7f8751_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_id'], name='vehicles_vehicle_06c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='locations_name_ce8723_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='locations_locatio_f7b031_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_latitud_4052bd_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_public'], name='locations_is_publ_546041_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['vehicle', 'status'], name='devices_vehicle_547b13_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_ping'], name='devices_last_pi_f246d1_idx'),
        ),
    ]
