# Generated by Django 4.2.27 on 2026-01-13 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Time when the data was recorded by the device')),
                ('latitude', models.FloatField(help_text='GPS latitude in decimal degrees')),
                ('longitude', models.FloatField(help_text='GPS longitude in decimal degrees')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in meters per second', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction of travel in degrees (0-360)', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Vehicle pitch angle in degrees (-90 to +90)', null=True)),
                ('roll', models.FloatField(blank=True, help_text='Vehicle roll angle in degrees (-180 to +180)', null=True)),
                ('accel_x', models.FloatField(blank=True, help_text='Acceleration in X-axis (m/s²)', null=True)),
                ('accel_y', models.FloatField(blank=True, help_text='Acceleration in Y-axis (m/s²)', null=True)),
                ('accel_z', models.FloatField(blank=True, help_text='Acceleration in Z-axis (m/s²)', null=True)),
                ('accel_magnitude', models.FloatField(blank=True, help_text='Magnitude of acceleration vector (m/s²)', null=True)),
                ('engine_status', models.BooleanField(default=False, help_text='True if engine is ON, False if OFF')),
                ('parking_status', models.BooleanField(default=False, help_text='True if vehicle is PARKED')),
                ('ble_proximity', models.BooleanField(default=False, help_text="True if owner's phone is nearby via BLE")),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Time when the server received this data')),
                ('device', models.ForeignKey(help_text='The device that sent this telemetry data', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='Devices.device')),
            ],
            options={
                'verbose_name_plural': 'Telemetry',
                'db_table': 'telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='telemetry_device__7e620a_idx'), models.Index(fields=['-timestamp'], name='telemetry_timesta_e5c802_idx'), models.Index(fields=['latitude', 'longitude'], name='telemetry_latitud_081673_idx'), models.Index(fields=['device', 'timestamp'], name='telemetry_device__6d4bf8_idx')],
            },
        ),
    ]
