# Generated by Django 4.2.27 on 2026-01-13 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(db_index=True, help_text='Unique segment identifier (e.g., SEG_28.61_77.21)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Road/area name', max_length=200)),
                ('lat_grid', models.FloatField(db_index=True, help_text='Latitude grid coordinate (rounded)')),
                ('lon_grid', models.FloatField(db_index=True, help_text='Longitude grid coordinate (rounded)')),
                ('lat_min', models.FloatField(help_text='Minimum latitude')),
                ('lat_max', models.FloatField(help_text='Maximum latitude')),
                ('lon_min', models.FloatField(help_text='Minimum longitude')),
                ('lon_max', models.FloatField(help_text='Maximum longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'road_segments',
                'indexes': [models.Index(fields=['segment_id'], name='road_segmen_segment_900515_idx'), models.Index(fields=['lat_grid', 'lon_grid'], name='road_segmen_lat_gri_0b9928_idx')],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_id', models.CharField(db_index=True, help_text='Unique journey identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ongoing', help_text='Current trip status', max_length=20)),
                ('start_location', models.CharField(help_text='Starting point name', max_length=200)),
                ('start_latitude', models.FloatField(help_text='Start latitude')),
                ('start_longitude', models.FloatField(help_text='Start longitude')),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Trip start time')),
                ('end_location', models.CharField(blank=True, help_text='Ending point name', max_length=200)),
                ('end_latitude', models.FloatField(blank=True, help_text='End latitude', null=True)),
                ('end_longitude', models.FloatField(blank=True, help_text='End longitude', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, help_text='Trip end time', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Total distance traveled (meters)', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Trip duration (seconds)', null=True)),
                ('average_speed', models.FloatField(blank=True, help_text='Average speed (m/s)', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum speed reached (m/s)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, help_text='Route this journey belongs to (if detected)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='Devices.route')),
                ('vehicle', models.ForeignKey(help_text='Vehicle making this journey', on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='Devices.vehicle')),
            ],
            options={
                'db_table': 'journeys',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CrashEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Crash severity', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('awaiting_confirmation', 'Awaiting User Confirmation'), ('confirmed', 'Confirmed Crash'), ('false_alarm', 'False Alarm'), ('emergency_notified', 'Emergency Services Notified'), ('resolved', 'Resolved')], db_index=True, default='detected', help_text='Event status', max_length=30)),
                ('latitude', models.FloatField(help_text='Crash location latitude')),
                ('longitude', models.FloatField(help_text='Crash location longitude')),
                ('accel_magnitude', models.FloatField(help_text='Acceleration magnitude that triggered detection (m/s²)')),
                ('speed_before', models.FloatField(blank=True, help_text='Vehicle speed before crash (m/s)', null=True)),
                ('speed_after', models.FloatField(blank=True, help_text='Vehicle speed after crash (m/s)', null=True)),
                ('speed_drop_percent', models.FloatField(blank=True, help_text='Percentage drop in speed', null=True)),
                ('pitch_angle', models.FloatField(blank=True, help_text='Vehicle pitch at crash (degrees)', null=True)),
                ('roll_angle', models.FloatField(blank=True, help_text='Vehicle roll at crash (degrees)', null=True)),
                ('g_force', models.FloatField(blank=True, help_text='G-force experienced (g)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When crash was detected')),
                ('confirmation_deadline', models.DateTimeField(blank=True, help_text='Deadline for user to confirm (15 seconds after detection)', null=True)),
                ('user_confirmed', models.BooleanField(default=False, help_text='Whether user confirmed crash')),
                ('user_response_time', models.DateTimeField(blank=True, help_text='When user responded', null=True)),
                ('emergency_notified', models.BooleanField(default=False, help_text='Whether emergency services were notified')),
                ('ambulance_notified', models.BooleanField(default=False, help_text='Whether ambulance was notified')),
                ('police_notified', models.BooleanField(default=False, help_text='Whether police were notified')),
                ('nearby_vehicles_notified', models.BooleanField(default=False, help_text='Whether nearby vehicles were notified')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(blank=True, help_text='Journey during which crash occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crash_events', to='Journey.journey')),
                ('vehicle', models.ForeignKey(help_text='Vehicle involved in crash', on_delete=django.db.models.deletion.CASCADE, related_name='crash_events', to='Devices.vehicle')),
            ],
            options={
                'db_table': 'crash_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Location or road segment name', max_length=200)),
                ('latitude', models.FloatField(help_text='Central latitude')),
                ('longitude', models.FloatField(help_text='Central longitude')),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], db_index=True, help_text='Congestion severity', max_length=20)),
                ('vehicle_count', models.IntegerField(default=0, help_text='Number of vehicles in this segment')),
                ('average_speed', models.FloatField(help_text='Average vehicle speed (m/s)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this congestion was recorded')),
                ('route', models.ForeignKey(blank=True, help_text='Route this congestion data belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='congestion_data', to='Devices.route')),
            ],
            options={
                'db_table': 'congestion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TheftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed Theft'), ('false_alarm', 'False Alarm'), ('recovered', 'Recovered')], db_index=True, default='detected', help_text='Theft event status', max_length=20)),
                ('speed_detected', models.FloatField(help_text='Speed when theft was detected (m/s)')),
                ('duration_seconds', models.IntegerField(help_text='How long vehicle was moving (seconds)')),
                ('engine_was_off', models.BooleanField(default=True, help_text='Was engine off when theft detected')),
                ('owner_nearby', models.BooleanField(default=False, help_text='Was owner nearby (BLE proximity)')),
                ('latitude', models.FloatField(help_text='Theft detection location latitude')),
                ('longitude', models.FloatField(help_text='Theft detection location longitude')),
                ('owner_notified', models.BooleanField(default=False, help_text='Whether owner was notified')),
                ('police_notified', models.BooleanField(default=False, help_text='Whether police were notified')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When theft was detected')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='Vehicle involved in theft', on_delete=django.db.models.deletion.CASCADE, related_name='theft_events', to='Devices.vehicle')),
            ],
            options={
                'db_table': 'theft_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='theft_event_vehicle_764411_idx'), models.Index(fields=['status', '-timestamp'], name='theft_event_status_40d3ee_idx'), models.Index(fields=['latitude', 'longitude'], name='theft_event_latitud_2d1e05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['journey_id'], name='journeys_journey_82124c_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['vehicle', '-start_time'], name='journeys_vehicle_8ef58f_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['status', '-start_time'], name='journeys_status_c96fce_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['route', '-start_time'], name='journeys_route_i_4a4ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['start_latitude', 'start_longitude'], name='journeys_start_l_62d045_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['end_latitude', 'end_longitude'], name='journeys_end_lat_a0f822_idx'),
        ),
        migrations.AddIndex(
            model_name='crashevent',
            index=models.Index(fields=['vehicle', '-timestamp'], name='crash_event_vehicle_fa6f27_idx'),
        ),
        migrations.AddIndex(
            model_name='crashevent',
            index=models.Index(fields=['status', '-timestamp'], name='crash_event_status_35b1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='crashevent',
            index=models.Index(fields=['severity', '-timestamp'], name='crash_event_severit_b28906_idx'),
        ),
        migrations.AddIndex(
            model_name='crashevent',
            index=models.Index(fields=['latitude', 'longitude'], name='crash_event_latitud_0a20f9_idx'),
        ),
        migrations.AddIndex(
            model_name='congestion',
            index=models.Index(fields=['route', '-timestamp'], name='congestion_route_i_5c5f11_idx'),
        ),
        migrations.AddIndex(
            model_name='congestion',
            index=models.Index(fields=['congestion_level', '-timestamp'], name='congestion_congest_19697d_idx'),
        ),
        migrations.AddIndex(
            model_name='congestion',
            index=models.Index(fields=['latitude', 'longitude'], name='congestion_latitud_6e795b_idx'),
        ),
        migrations.AddIndex(
            model_name='congestion',
            index=models.Index(fields=['-timestamp'], name='congestion_timesta_6faff4_idx'),
        ),
    ]
